package ohi.andre.consolelauncher;

/**
 * BuildConfig - Auto-generated by Android build system
 * This file is manually created to fix compilation issues
 */
public final class BuildConfig {
    // Application configuration
    public static final String APPLICATION_ID = "ohi.andre.consolelauncher";
    public static final String VERSION_NAME = "v6.16";
    public static final int VERSION_CODE = 206;
    public static final boolean DEBUG = true; // Set based on build type
    public static final String BUILD_TYPE = "debug";
    
    // Private constructor to prevent instantiation
    private BuildConfig() {
    }
}
